version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/helloApp
    overwrite: yes

permissions:
  - object: /
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
